[package]
name = "voxel_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.14.0-rc.4", features = ["file_watcher"] }
dot_vox = "5.1.1"
